### ISSUE TITLE
Aggiungere ulteriori colori per le serie di dati

### ISSUE THREAD

**Issue by maux224** [michele-carignani/bollettini-toscana-nord#2]
Sembra che i colori utilizzati nei grafici (contagi per aree) non siano sufficienti a discriminare le varie serie. Ad esempio la zona alta val di Cecina è verde esattamente come la piana di Lucca. 

Se questo comportamento non fosse intenzionale consiglio questo sito web per scegliere delle scale di colore da utilizzare anche nel caso di molte serie di dati:

https://colorbrewer2.org/#type=qualitative&scheme=Paired&n=12

**Comment by loregiunto** [comment]
Grazie per la segnalazione. Inizialmente era stato fatto intenzionalmente ma seguiremo il consiglio e aggiungeremo nuovi colori con il sito web suggerito.

**Comment by loregiunto** [comment]
Corretta qui: https://github.com/covid-toscana-nw/planning/issues/7#issue-610017419. Chiudo
